### ISSUE TITLE
Vim vs notepad

### ISSUE THREAD

**Issue by icobani** [Trendyol/code-playground#2]
Merhaba mevcutta sanırım vim editörünü kullanıyor. bunu da parametrik olarak örneğin notepad kullanacak şeklide bir güncelleme yapabilmemiz mümkün mü ?

**Comment by gunerhuseyin** [comment]
Selam @icobani `PLAYGROUND_ENVIRONMENT` environment variable i setleyerek bunu yapabilirsin.

Ornegin: `export PLAYGROUND_ENVIRONMENT="subl -w"` ile editoru sublime olarak degistirebilirsin
